# Handles the build process for the theme, which includes creating and storing
# an artifact in the workflow.

name: Create Artifact

on:
  workflow_call:
    inputs:
      retention-days:
        required: false
        type: number
        default: 1

env:
  ARTIFACT_PATH: 'go-theme'

# First build our theme, the create and store the artifact.
jobs:
  build:
    name: Create Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Setup WP-CLI
        uses: godaddy-wordpress/setup-wp-cli@main

      # Yarn is still required on this project, so we need to make sure it is
      # installed globally.
      - name: Install yarn
        run: npm i -g yarn

      - name: Build theme
        run: |
          composer install
          yarn install --immutable
          yarn setup

      - name: Create translations
        run: |
          yarn makepot

      - name: Create distribution artifact
        run: |
          rsync --archive --recursive --filter='protect .git' --delete --prune-empty-dirs --include-from="$GITHUB_WORKSPACE/.distinclude" "$GITHUB_WORKSPACE/" "$GITHUB_WORKSPACE/$ARTIFACT_PATH/"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_PATH }}
          path: ${{ env.ARTIFACT_PATH }}
          if-no-files-found: error
          retention-days: ${{ inputs.retention-days }}
