name: WIP Create Release

on:
  push:
    branches:
      - migrate/circleci-to-github-actions

jobs:
  build:
    name: Build
    uses: ./.github/workflows/wip-create-artifact.yml

  release:
    runs-on: ubuntu-latest
    name: Release theme
    needs: build
    steps:
      - name: hello
        run: |
          echo "hello world"
