name: WIP Tests

on:
  pull_request:
    branches:
      - master

jobs:
  php:
    name: PHP Unit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Setup WP-CLI
        uses: godaddy-wordpress/setup-wp-cli@1

      - name: Install dependencies and build
        run: |
          npm i -g yarn
          yarn run setup

      - name: Setup wp-env
        uses: godaddy-wordpress/setup-wp-env@main
        with:
          core: 'WordPress/WordPress#6.0'
          phpVersion: '7.4'
          themes: '["."]'

      - name: Start and setup environment
        run: |
          wp-env start
          wp-env run tests-cli "wp plugin install coblocks woocommerce --activate"
          wp-env run tests-cli "wp theme activate go"

      - name: Run tests
        run: |
          wp-env run phpunit "composer install --working-dir=html/wp-content/themes/go/"
          wp-env run phpunit "composer run test --working-dir=html/wp-content/themes/go/"
